buy-main-menu-title: "PiggyShop Buy UI"
buy-category-menu-title: "{CATEGORY}"
buy-item-menu-title: "Buy {ITEM}"
buy-item-confirm-menu-title: "Confirm Transaction"
buy-categories:
  - name: "Blocks"
    image: "http://www.blocksandgold.com//media/catalog/product/cache/3/image/200x/6cffa5908a86143a54dc6ad9b8a7c38e/c/o/cobblestone_6.png"
    image-type: 1
    items:
      - menu-name: "Stone"
        id: 1
        damage: 0
        price: 50
        image: "textures/blocks/stone"
        image-type: 0
      - menu-name: "Grass"
        id: 2
        damage: 0
        price: 100
        image: "textures/blocks/grass_side_carried"
        image-type: 0
      - menu-name: "Dirt"
        id: 3
        damage: 0
        price: 75
        image: "textures/blocks/dirt"
        image-type: 0
      - menu-name: "Cobblestone"
        id: 4
        damage: 0
        price: 50
        image: "textures/blocks/cobblestone"
        image-type: 0
      - menu-name: "Obsidian"
        id: 49
        damage: 0
        price: 250
        image: "textures/blocks/obsidian"
        image-type: 0
      - menu-name: "Sand"
        id: 12
        damage: 0
        price: 20
        image: "textures/blocks/sand"
        image-type: 0
      - menu-name: "Glass"
        id: 20
        damage: 0
        price: 35
        image: "textures/blocks/glass"
        image-type: 0
      - menu-name: "GlowStone"
        id: 89
        damage: 0
        price: 70
        image: "textures/blocks/glowstone"
        image-type: 0
      - menu-name: "BookShelf"
        id: 169
        damage: 0
        price: 175
        image: "textures/blocks/bookshelf"
        image-type: 0
      - menu-name: "wood"
        id: 17
        damage: 0
        price: 50
        image: "textures/blocks/wood"
        image-type: 0
      - menu-name: "Iron Block"
        id: 42
        damage: 0
        price: 500
        image: "textures/items/iron_block"
        image-type: 0
      - menu-name: "Gold Block"
        id: 41
        damage: 0
        price: 750
        image: "textures/blocks/gold_block"
        image-type: 0
      - menu-name: "Emerald Block"
        id: 133
        damage: 0
        price: 1000
        image: "textures/blocks/emerald_block"
        image-type: 0
      - menu-name: "Quartz Block"
        id: 155
        damage: 0
        price: 70
        image: "textures/blocks/quartz_block_side"
        image-type: 0
  - name: "Food"
    image: "https://media.forgecdn.net/avatars/64/819/636156733139658109.png"
    image-type: 1
    items:
      - menu-name: "Steak"
        id: 364
        damage: 0
        price: 30
        image: "textures/items/beef_cooked"
        image-type: 0
      - menu-name: "Cooked Chicken"
        id: 366
        damage: 0
        price: 25
        image: "textures/items/chicken_cooked"
        image-type: 0
      - menu-name: "Cooked Pork"
        id: 320
        damage: 0
        price: 36
        image: "textures/items/porkchop_cooked"
        image-type: 0
      - menu-name: "Bread"
        id: 297
        damage: 0
        price: 15
        image: "textures/items/bread"
        image-type: 0
      - menu-name: "Golden Apple"
        id: 322
        damage: 0
        price: 300
        image: "textures/items/apple_golden"
        image-type: 0
  - name: "Ores"
    image: "http://saltypixel.ga/textures/items/coal.png"
    image-type: 1
    items:
      - menu-name: "Coal"
        id: 263
        damage: 0
        price: 120
        image: "textures/items/coal"
        image-type: 0
      - menu-name: "Diamond"
        id: 264
        damage: 0
        price: 152
        image: "textures/items/diamond"
        image-type: 0
      - menu-name: "Iron"
        id: 265
        damage: 0
        price: 50
        image: "textures/items/iron_ingot"
        image-type: 0
      - menu-name: "Gold"
        id: 266
        damage: 0
        price: 75
        image: "textures/items/gold_ingot"
        image-type: 0
      - menu-name: "Emerald"
        id: 388
        damage: 0
        price: 200
        image: "textures/items/emerald"
        image-type: 0
  - name: "Miscellaneous"
    image: "https://media.forgecdn.net/avatars/64/819/636156733139658109.png"
    image-type: 1
    items:
      - menu-name: "Torch"
        id: 50
        damage: 0
        price: 5
        image: "textures/items/torch_on"
        image-type: 0
      - menu-name: "Lava"
        id: 10
        damage: 0
        price: 500
        image: "textures/items/bucket_lava"
        image-type: 0
      - menu-name: "Water"
        id: 8
        damage: 0
        price: 36
        image: "textures/items/bucket_water"
        image-type: 0
      - menu-name: "Elytra"
        id: 444
        damage: 0
        price: 250000
        image: "textures/items/elytra"
        image-type: 0
      - menu-name: "Grappling Hook"
        id: 346
        damage: 0
        price: 15000
        image: "https://lh3.googleusercontent.com/VAiw5YFbLYhlFA0KHcIde5_A40EaLN9K1uj7YHP31i8HKgwMFbJf_stzJYHCKZQuRCiEVb5Z8KJuiv6mcOIXQA"
        image-type: 0
  - name: "Farming"
    image: "http://saltypixel.ga/textures/items/coal.png"
    image-type: 1
    items:
      - menu-name: "Pumpkin"
        id: 86
        damage: 0
        price: 120
        image: "textures/items/seeds_pumpkin"
        image-type: 0
      - menu-name: "Sugar Cane"
        id: 338
        damage: 0
        price: 152
        image: "textures/items/sugar"
        image-type: 0
      - menu-name: "Melon"
        id: 362
        damage: 0
        price: 60
        image: "textures/items/seeds_melon"
        image-type: 0
      - menu-name: "Wheat"
        id: 296
        damage: 0
        price: 75
        image: "textures/items/seeds_wheat"
        image-type: 0
      - menu-name: "Carrot"
        id: 391
        damage: 0
        price: 200
        image: "textures/items/carrot"
        image-type: 0
sell-main-menu-title: "PiggyShop Sell UI"
sell-category-menu-title: "{CATEGORY}"
sell-item-menu-title: "Sell {ITEM}"
sell-item-confirm-menu-title: "Confirm Transaction"
sell-categories:
  - name: "Blocks"
    image: "http://www.blocksandgold.com//media/catalog/product/cache/3/image/200x/6cffa5908a86143a54dc6ad9b8a7c38e/c/o/cobblestone_6.png"
    image-type: 1
    items:
      - menu-name: "Stone"
        id: 1
        damage: 0
        price: 2.5
        image: "textures/blocks/stone"
        image-type: 0
      - menu-name: "Grass"
        id: 2
        damage: 0
        price: 5
        image: "textures/blocks/grass_side_carried"
        image-type: 0
      - menu-name: "Dirt"
        id: 3
        damage: 0
        price: 0.5
        image: "textures/blocks/dirt"
        image-type: 0
  - name: "Food"
    image: "https://media.forgecdn.net/avatars/64/819/636156733139658109.png"
    image-type: 1
    items:
      - menu-name: "Steak"
        id: 364
        damage: 0
        price: 5
        image: "textures/items/beef_cooked"
        image-type: 0
      - menu-name: "Cooked Chicken"
        id: 366
        damage: 0
        price: 5
        image: "textures/items/chicken_cooked"
        image-type: 0
      - menu-name: "Bread"
        id: 297
        damage: 0
        price: 2.5
        image: "textures/items/bread"
        image-type: 0
messages:
  buy-item-information: "{ITEM} cost ${PRICE} each."
  sell-item-information: "{ITEM} sell for ${PRICE} each."
  buy-item-confirmation: "Are you sure you would like to buy {COUNT}x {ITEM} for ${PRICE}."
  not-enough-money: "You do not have the required money to buy {COUNT}x {ITEM}. You are missing ${MISSING}."
  successfully-bought-item: "You have successfully bought {COUNT}x {ITEM} for ${PRICE}."
  sell-item-confirmation: "Are you sure you would like to sell {COUNT}x {ITEM} for ${PRICE}."
  missing-items: "You do not have {COUNT}x {ITEM}."
  successfully-sold-item: "You have successfully sold {COUNT}x {ITEM} for ${PRICE}."
  back-button: "Back"
